#!/bin/bash

source activate "${CONDA_DEFAULT_ENV}"

mkdir build
cd build

BUILD_CONFIG=Release

# use globs to take into account various possible suffixes: m, u, d
PYTHON_LIBRARY=`ls -d ${PREFIX}/lib/libpython* | head -n 1`
PYTHON_INCLUDE=`ls -d ${PREFIX}/include/python* | head -n 1`

if [ `uname` = "Linux" ]; then
    LINUX=true
elif [ `uname` = "Darwin" ]; then
    DARWIN=true
fi

cmake .. -G "Ninja" \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=${BUILD_CONFIG} \
    -DCMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
    -DCMAKE_INSTALL_RPATH:PATH="${PREFIX}/lib" \
    -DBUILD_DOCUMENTATION:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DPYTHON_EXECUTABLE:FILEPATH=${PYTHON} \
    -DPYTHON_INCLUDE_DIR:PATH=${PYTHON_INCLUDE} \
    -DPYTHON_LIBRARY:FILEPATH=${PYTHON_LIBRARY} \
    -DVTK_ENABLE_VTKPYTHON:BOOL=OFF \
    -DVTK_WRAP_PYTHON:BOOL=ON \
    -DVTK_PYTHON_VERSION:STRING=${PY_VER} \
    -DVTK_INSTALL_PYTHON_MODULE_DIR:PATH=${SP_DIR} \
    -DVTK_HAS_FEENABLEEXCEPT:BOOL=OFF \
    -DVTK_USE_OFFSCREEN:BOOL=OFF \
    -DVTK_RENDERING_BACKEND=OpenGL2 \
    -DModule_vtkRenderingMatplotlib=ON \
    -DModule_vtkRenderingOSPRay=ON \
    -DOSPRAY_INSTALL_DIR="${PREFIX}/lib" \
    -Dembree_DIR="${PREFIX}/lib" \
    -DVTK_USE_SYSTEM_ZLIB:BOOL=ON \
    -DVTK_USE_SYSTEM_FREETYPE:BOOL=ON \
    -DVTK_USE_SYSTEM_LIBXML2:BOOL=ON \
    -DVTK_USE_SYSTEM_PNG:BOOL=ON \
    -DVTK_USE_SYSTEM_JPEG:BOOL=ON \
    -DVTK_USE_SYSTEM_TIFF:BOOL=ON \
    -DVTK_USE_SYSTEM_EXPAT:BOOL=ON \
    -DVTK_USE_SYSTEM_HDF5:BOOL=ON \
    ${DARWIN:+-DCMAKE_CXX_STANDARD=11} \
    ${DARWIN:+-DVTK_USE_COCOA=ON} \
    ${DARWIN:+-DVTK_USE_TK=OFF} \
    ${LINUX:+-DVTK_USE_SYSTEM_JSONCPP:BOOL=OFF} \
    ${LINUX:+-DVTK_OPENGL_HAS_OSMESA:BOOL=ON} \
    ${LINUX:+-DOPENGL_INCLUDE_DIR="$PREFIX/include"} \
    ${LINUX:+-DOPENGL_gl_LIBRARY="$PREFIX/lib/libGL.so"} \
    ${LINUX:+-DOSMESA_INCLUDE_DIR:PATH="$PREFIX/include"} \
    ${LINUX:+-DOSMESA_LIBRARY:FILEPATH="$PREFIX/lib/libOSMesa.so"} \
    ${LINUX:+-DVTK_USE_X:BOOL=ON} \
    ${SCREEN_ARGS[@]}

ninja install
