mkdir build
cd build

set DCMTK_HOME=%PREFIX%

cmake .. -G "Ninja" ^
	-DCMAKE_FIND_ROOT_PATH=%PREFIX% ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
	-DCMAKE_BUILD_TYPE:STRING=Release ^
	-DDCMTK_WITH_OPENSSL:BOOL=TRUE ^
	-DDCMTK_WITH_PNG:BOOL=TRUE ^
	-DDCMTK_WITH_THREADS:BOOL=TRUE ^
	-DDCMTK_WITH_TIFF:BOOL=TRUE ^
	-DDCMTK_WITH_XML:BOOL=TRUE ^
	-DDCMTK_WITH_ZLIB:BOOL=TRUE ^
	-DBUILD_SHARED_LIBS:BOOL=TRUE ^
	-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=TRUE

ninja install
